project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: labs.qmd
        text: Labs
        menu:
         - href: Labs\Lab 1\lab1.qmd
           text: Lab 1
         - href: Labs\Lab 2\lab2.qmd
           text: Lab 2
         - href: Labs\Lab 3\lab3.qmd
           text: Lab 3
         - href: Labs\Lab 4\lab4.qmd
           text: Lab 4
         - href: Labs\Lab 5\lab5.qmd
           text: Lab 5
         - href: Labs\Lab 6\lab6.qmd
           text: Lab 6
         - href: Labs\Lab 7\lab7.qmd
           text: Lab 7
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



